name: macos-build-arm

on: [push, pull_request, workflow_dispatch]
  
jobs:
 build-macos-arm:
    strategy:
      fail-fast: false
      matrix:
        arch: [ arm64 ]

    name: build-macos-${{ matrix.arch }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
       lfs: 'true'
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Set env
      id: env
      run: |
        xmake g -c
        xmake l setup.lua
    - name: Shipping
      run: |
        xmake f -m release -y --policies=build.ccache:n --arch=${{ matrix.arch }}
        xmake -y -v
    - name: UploadShipping
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ matrix.arch }}
        path: build